export type IconName = keyof typeof icons

export const icons = {
	stopwatch: 'i-fa-solid-stopwatch',
	alarm: 'i-fa-solid-bell',
	timer: 'i-fa-solid-hourglass-half',
	clock: 'i-fa-solid-clock',
	play: 'i-fa-solid-play',
	pause: 'i-fa-solid-pause',
	reload: 'i-fa-solid-redo-alt',
	edit: 'i-fa-solid-pencil-alt',
	caret: 'i-fa-solid-caret-down',
	settings: 'i-fa-solid-cog',
	twitter: 'i-fa-brands-twitter',
	github: 'i-fa-brands-github',
	stop: 'i-fa-solid-stop',
	info: 'i-fa-solid-info',
	trash: 'i-fa-solid-trash',
	plus: 'i-fa-solid-plus',
	light: 'i-fa-solid-sun',
	dark: 'i-fa-solid-moon',
	share: 'i-fa-solid-share',
	search: 'i-fa-solid-search',
	text: 'i-fa-solid-pen-nib',
	number: 'i-fa-solid-hashtag',
	calc: 'i-fa-solid-calculator',
	date: 'i-fa-solid-calendar',
	color: 'i-fa-solid-palette',
	code: 'i-fa-solid-code',
	expand: 'i-fa-solid-expand',
	compress: 'i-fa-solid-compress',
	file: 'i-fa-solid-file',
	tree: 'i-fa6-solid-chart-gantt',
	diagram: 'i-fa6-solid-chart-diagram',
}
